In [2]:
import pandas as pd
import os
os.chdir(r"C:\Users\Bisbii\Desktop\lipids")

In [3]:
model_compound_ng = pd.read_csv("ngaditana/model_compound_ng.csv")
model_compound_pl = pd.read_csv("plutheri/model_compound_pl.csv")

In [4]:
#remove duplicate external_identifiers, keeping the first
model_compound_ng = model_compound_ng.drop_duplicates(subset="external_identifier", keep="first")
model_compound_pl = model_compound_pl.drop_duplicates(subset="external_identifier", keep="first")

In [5]:
#metabolites that are in model_compound_ng but not in model_compound_pl
ng_not_pl = model_compound_ng[~model_compound_ng.external_identifier.isin(model_compound_pl.external_identifier)]

In [6]:
ng_not_pl.to_csv("plutheri/model_compound_from_ng.csv", index=False)

In [7]:
model_reaction_labels_ng = pd.read_csv("ngaditana/model_reaction_labels.csv")
model_reaction_labels_pl = pd.read_csv("plutheri/model_reaction_labels.csv")

In [8]:
ng_not_in_pl = model_reaction_labels_ng[~model_reaction_labels_ng.name.isin(model_reaction_labels_pl.name)]
ng_not_in_pl.head()

,idreaction_label,equation,isGeneric,isNonEnzymatic,isSpontaneous,name,source
4190,4191,4-Aminobutyraldehyde <=> 1-Pyrroline + H2O,0,0,1,R07408,MANUAL
5362,5363,Putrescine + 2-Oxoglutarate <=> 1-Pyrroline + ...,0,0,0,R10064,KEGG
6297,6298,CDP-glycerol + (Glycerophosphate)n => CMP + (G...,0,0,0,R04042,KEGG
6309,6310,UDP-glucose + (Glycerophosphate)n <=> UDP + al...,0,0,0,R04041,KEGG
7312,7313,CoA + Octadecanoic acid + ATP => Stearoyl-CoA ...,1,0,0,RXN-16380,MANUAL

In [9]:
ng_not_in_pl.to_csv("plutheri/model_reaction_labels_from_ng.csv", index=False)

In [10]:
model_reaction_ng = pd.read_csv("ngaditana/model_reaction.csv")
model_reaction_pl = pd.read_csv("plutheri/model_reaction.csv")

In [11]:
model_reaction_ng_to_add = model_reaction_ng.loc[model_reaction_ng.model_reaction_labels_idreaction_label.isin(ng_not_in_pl.idreaction_label)]

In [12]:
model_reaction_ng_to_add['name'] = model_reaction_ng_to_add['model_reaction_labels_idreaction_label'].map(ng_not_in_pl.set_index('idreaction_label')['name'])

C:\Users\Bisbii\AppData\Local\Temp\ipykernel_28528\2350812274.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  model_reaction_ng_to_add['name'] = model_reaction_ng_to_add['model_reaction_labels_idreaction_label'].map(ng_not_in_pl.set_index('idreaction_label')['name'])

In [13]:
# drop duplicate names, keeping first
model_reaction_ng_to_add = model_reaction_ng_to_add.drop_duplicates(subset="name", keep="first")
model_reaction_ng_to_add.head()

,idreaction,boolean_rule,inModel,lowerBound,notes,upperBound,compartment_idcompartment,model_reaction_labels_idreaction_label,name
1022,23926,NaN,1,0.0,NaN,999999.0,48,7313,RXN-16380
1049,23953,NaN,1,0.0,NaN,10000.0,44,10286,R12479
1073,23977,NaN,0,0.0,NaN,10000.0,48,10282,R05979
1146,24050,NaN,0,0.0,NaN,10000.0,48,10288,R05984
1405,24309,NaN,1,0.0,NaN,10000.0,40,10262,R09394

In [14]:
model_reaction_labels_after_import = pd.read_csv(r"plutheri/model_reaction_labels_after_import.csv")
model_reaction_labels_after_import.head()

,idreaction_label,equation,isGeneric,isNonEnzymatic,isSpontaneous,name,source
0,1,Choloyl-CoA + Glycine => CoA + Glycocholate,0.0,0.0,0.0,R03718,KEGG
1,2,"Propanoyl-CoA + Choloyl-CoA <=> CoA + 3alpha,7...",0.0,0.0,0.0,R03719,KEGG
2,3,UDP-glucose + trans-2-Hydroxycinnamate => UDP ...,0.0,0.0,0.0,R03710,KEGG
3,4,Albendazole + Oxygen + NADPH + H+ => Albendazo...,0.0,0.0,0.0,R03712,KEGG
4,5,Actinomycin + H2O => Actinomycinic monolactone,0.0,0.0,0.0,R03711,KEGG

In [15]:
model_reaction_ng_to_add.head()

,idreaction,boolean_rule,inModel,lowerBound,notes,upperBound,compartment_idcompartment,model_reaction_labels_idreaction_label,name
1022,23926,NaN,1,0.0,NaN,999999.0,48,7313,RXN-16380
1049,23953,NaN,1,0.0,NaN,10000.0,44,10286,R12479
1073,23977,NaN,0,0.0,NaN,10000.0,48,10282,R05979
1146,24050,NaN,0,0.0,NaN,10000.0,48,10288,R05984
1405,24309,NaN,1,0.0,NaN,10000.0,40,10262,R09394

In [16]:
model_reaction_ng_to_add.drop(["name"], axis=1, inplace=True)
model_reaction_ng_to_add.to_csv("plutheri/model_reaction_to_add.csv", index=False)

In [17]:
model_stoichiometry_ng = pd.read_csv("ngaditana/model_stoichiometry.csv")
model_compound_pl_after_import = pd.read_csv("plutheri/model_compound_after_import.csv")

In [18]:
model_reaction_reaction_labels_pl = pd.read_csv("plutheri/model_reaction_model_reaction_labels_after_import.csv")
model_reaction_reaction_labels_ng = pd.read_csv("ngaditana/model_reaction_model_reaction_labels_after_import.csv")

In [19]:
id_reaction_added = model_reaction_ng_to_add.loc[model_reaction_ng_to_add.idreaction.isin(model_reaction_ng_to_add.idreaction)]
id_reaction_added.head()

,idreaction,boolean_rule,inModel,lowerBound,notes,upperBound,compartment_idcompartment,model_reaction_labels_idreaction_label
1022,23926,NaN,1,0.0,NaN,999999.0,48,7313
1049,23953,NaN,1,0.0,NaN,10000.0,44,10286
1073,23977,NaN,0,0.0,NaN,10000.0,48,10282
1146,24050,NaN,0,0.0,NaN,10000.0,48,10288
1405,24309,NaN,1,0.0,NaN,10000.0,40,10262

In [20]:
model_reaction_reaction_labels_pl.head()

,idreaction,boolean_rule,inModel,lowerBound,notes,upperBound,compartment_idcompartment,model_reaction_labels_idreaction_label,idreaction_label,equation,isGeneric,isNonEnzymatic,isSpontaneous,name,source
0,1,NaN,0,0.0,NaN,999999.0,NaN,1,1,Choloyl-CoA + Glycine => CoA + Glycocholate,0,0,0,R03718,KEGG
1,2,NaN,0,-999999.0,NaN,999999.0,NaN,2,2,"Propanoyl-CoA + Choloyl-CoA <=> CoA + 3alpha,7...",0,0,0,R03719,KEGG
2,3,NaN,0,0.0,NaN,999999.0,NaN,3,3,UDP-glucose + trans-2-Hydroxycinnamate => UDP ...,0,0,0,R03710,KEGG
3,4,NaN,0,0.0,NaN,999999.0,NaN,4,4,Albendazole + Oxygen + NADPH + H+ => Albendazo...,0,0,0,R03712,KEGG
4,5,NaN,0,0.0,NaN,999999.0,NaN,5,5,Actinomycin + H2O => Actinomycinic monolactone,0,0,0,R03711,KEGG

In [21]:
id_reaction_added.head()

,idreaction,boolean_rule,inModel,lowerBound,notes,upperBound,compartment_idcompartment,model_reaction_labels_idreaction_label
1022,23926,NaN,1,0.0,NaN,999999.0,48,7313
1049,23953,NaN,1,0.0,NaN,10000.0,44,10286
1073,23977,NaN,0,0.0,NaN,10000.0,48,10282
1146,24050,NaN,0,0.0,NaN,10000.0,48,10288
1405,24309,NaN,1,0.0,NaN,10000.0,40,10262

In [22]:
model_stoichiometry_ng_added = model_stoichiometry_ng.loc[model_stoichiometry_ng.model_reaction_idreaction.isin(id_reaction_added.idreaction)]
model_stoichiometry_ng_added.head()

,idstoichiometry,stoichiometric_coefficient,model_compartment_idcompartment,model_compound_idcompound,model_reaction_idreaction
48353,105336,-1.0,48,2281,23977
48354,105337,-1.0,48,8507,23977
48355,105338,1.0,48,3487,23977
48356,105339,1.0,48,8508,23977
48571,105660,-2.0,48,2281,24050

In [23]:
model_reaction_reaction_labels_ng_added = model_reaction_reaction_labels_ng.loc[model_reaction_reaction_labels_ng.idreaction.isin(id_reaction_added.idreaction)]

In [24]:
model_reaction_reaction_labels_ng_added.head()

,idreaction,boolean_rule,inModel,lowerBound,notes,upperBound,compartment_idcompartment,model_reaction_labels_idreaction_label,idreaction_label,equation,isGeneric,isNonEnzymatic,isSpontaneous,name,source
1022,23926,NaN,1,0.0,NaN,999999.0,48,7313,7313,CoA + Octadecanoic acid + ATP => Stearoyl-CoA ...,1,0,0,RXN-16380,MANUAL
1049,23953,NaN,1,0.0,NaN,10000.0,44,10286,10286,3 H2O + (GlcNAc)2 (Man)8 (Asn)1 => 3 D-Mannose...,0,0,0,R12479,MANUAL
1073,23977,NaN,0,0.0,NaN,10000.0,48,10282,10282,H2O + (Glc)3 (GlcNAc)2 (Man)9 (Asn)1 => beta-D...,0,0,0,R05979,MANUAL
1146,24050,NaN,0,0.0,NaN,10000.0,48,10288,10288,2 H2O + (GlcNAc)3 (Man)5 (Asn)1 => 2 alpha-D-M...,0,0,0,R05984,MANUAL
1405,24309,NaN,1,0.0,NaN,10000.0,40,10262,10262,NADH + S-Adenosyl-L-methionine + GTP => 5'-Deo...,0,0,0,R09394,MANUAL

In [25]:
model_reaction_reaction_labels_pl_added = model_reaction_reaction_labels_pl.loc[model_reaction_reaction_labels_pl.name.isin(model_reaction_reaction_labels_ng_added.name)]

In [26]:
model_stoichiometry_ng_added.head()

,idstoichiometry,stoichiometric_coefficient,model_compartment_idcompartment,model_compound_idcompound,model_reaction_idreaction
48353,105336,-1.0,48,2281,23977
48354,105337,-1.0,48,8507,23977
48355,105338,1.0,48,3487,23977
48356,105339,1.0,48,8508,23977
48571,105660,-2.0,48,2281,24050

In [27]:
model_reaction_reaction_labels_pl_added['old_idreaction'] = model_reaction_reaction_labels_pl_added['name'].map(model_reaction_reaction_labels_ng_added.set_index('name')['idreaction'])
model_reaction_reaction_labels_pl_added.head()

C:\Users\Bisbii\AppData\Local\Temp\ipykernel_28528\533389770.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  model_reaction_reaction_labels_pl_added['old_idreaction'] = model_reaction_reaction_labels_pl_added['name'].map(model_reaction_reaction_labels_ng_added.set_index('name')['idreaction'])

,idreaction,boolean_rule,inModel,lowerBound,notes,upperBound,compartment_idcompartment,model_reaction_labels_idreaction_label,idreaction_label,equation,isGeneric,isNonEnzymatic,isSpontaneous,name,source,old_idreaction
11443,12683,NaN,0,0.0,NaN,999999.0,NaN,12687,12687,CoA + Octadecanoic acid + ATP => Stearoyl-CoA ...,0,0,0,RXN-16380,MANUAL,23926
11444,12684,NaN,0,0.0,NaN,10000.0,NaN,12714,12714,3 H2O + (GlcNAc)2 (Man)8 (Asn)1 => 3 D-Mannose...,0,0,0,R12479,MANUAL,23953
11445,12685,NaN,0,0.0,NaN,10000.0,NaN,12710,12710,H2O + (Glc)3 (GlcNAc)2 (Man)9 (Asn)1 => beta-D...,0,0,0,R05979,MANUAL,23977
11446,12686,NaN,0,0.0,NaN,10000.0,NaN,12716,12716,2 H2O + (GlcNAc)3 (Man)5 (Asn)1 => 2 alpha-D-M...,0,0,0,R05984,MANUAL,24050
11447,12687,NaN,0,0.0,NaN,10000.0,NaN,12692,12692,NADH + S-Adenosyl-L-methionine + GTP => 5'-Deo...,0,0,0,R09394,MANUAL,24309

In [28]:
# update model_reaction_idreaction in model_stoichiometry_ng_added with the new idreaction mapping the old_idreaction to idreaction
model_stoichiometry_ng_idreaction = model_stoichiometry_ng_added.copy()
model_stoichiometry_ng_idreaction['model_reaction_idreaction'] = model_stoichiometry_ng_idreaction['model_reaction_idreaction'].map(model_reaction_reaction_labels_pl_added.set_index('old_idreaction')['idreaction'])

In [29]:
model_stoichiometry_ng_added.head() # R05979

,idstoichiometry,stoichiometric_coefficient,model_compartment_idcompartment,model_compound_idcompound,model_reaction_idreaction
48353,105336,-1.0,48,2281,23977
48354,105337,-1.0,48,8507,23977
48355,105338,1.0,48,3487,23977
48356,105339,1.0,48,8508,23977
48571,105660,-2.0,48,2281,24050

In [30]:
model_stoichiometry_ng_idreaction.head()

,idstoichiometry,stoichiometric_coefficient,model_compartment_idcompartment,model_compound_idcompound,model_reaction_idreaction
48353,105336,-1.0,48,2281,12685
48354,105337,-1.0,48,8507,12685
48355,105338,1.0,48,3487,12685
48356,105339,1.0,48,8508,12685
48571,105660,-2.0,48,2281,12686

In [31]:
model_compound_pl_added = model_compound_pl_after_import.loc[model_compound_pl_after_import.external_identifier.isin(ng_not_pl.external_identifier)]

In [32]:
# add column 'old_idcompound' to model_compound_pl_added
model_compound_pl_after_import['old_idcompound'] = model_compound_pl_after_import['external_identifier'].map(model_compound_ng.set_index('external_identifier')['idcompound'])
# drop rows where old_idcompound is NaN
model_compound_pl_after_import = model_compound_pl_after_import.dropna(subset=['old_idcompound']).astype({'old_idcompound': 'int64'})
model_compound_pl_after_import.head()

,idcompound,charge,entry_type,external_identifier,formula,hasBiologicalRoles,inchi,molecular_weight,name,neutral_formula,smiles,old_idcompound
0,1,NaN,COMPOUND,C00420,C12H22O11(C6H10O5)n,0.0,NaN,NaN,Polysaccharide,NaN,NaN,1
1,2,NaN,COMPOUND,C01752,C10H8O4,0.0,NaN,192.1681,Scopoletin,NaN,NaN,2
2,3,NaN,COMPOUND,C01753,C29H50O,0.0,NaN,414.7067,beta-Sitosterol,NaN,NaN,3
3,4,NaN,COMPOUND,C01755,CHNS,0.0,NaN,59.0903,Thiocyanate,NaN,NaN,4
4,5,NaN,COMPOUND,C01756,C5H4N4S,0.0,NaN,152.1771,Thiopurine,NaN,NaN,5

In [33]:
# update model_compound_idcompound in model_stoichiometry_ng_idreaction with the new idcompound mapping the old_idcompound to idcompound
model_stoichiometry_ng_idcompound = model_stoichiometry_ng_idreaction.copy()
model_stoichiometry_ng_idcompound['model_compound_idcompound'] = model_stoichiometry_ng_idcompound['model_compound_idcompound'].map(model_compound_pl_after_import.set_index('old_idcompound')['idcompound'])  # 2281
model_stoichiometry_ng_idcompound['model_compound_idcompound'] = model_stoichiometry_ng_idcompound['model_compound_idcompound'].astype('Int64')

In [34]:
model_stoichiometry_ng_idreaction.head()

,idstoichiometry,stoichiometric_coefficient,model_compartment_idcompartment,model_compound_idcompound,model_reaction_idreaction
48353,105336,-1.0,48,2281,12685
48354,105337,-1.0,48,8507,12685
48355,105338,1.0,48,3487,12685
48356,105339,1.0,48,8508,12685
48571,105660,-2.0,48,2281,12686

In [35]:
model_stoichiometry_ng_idcompound.head()

,idstoichiometry,stoichiometric_coefficient,model_compartment_idcompartment,model_compound_idcompound,model_reaction_idreaction
48353,105336,-1.0,48,1237,12685
48354,105337,-1.0,48,8737,12685
48355,105338,1.0,48,3996,12685
48356,105339,1.0,48,8738,12685
48571,105660,-2.0,48,1237,12686

In [36]:
model_stoichiometry_ng_idcompound["model_compartment_idcompartment"] = 1
model_stoichiometry_ng_idcompound.to_csv("plutheri/model_stoichiometry_to_add.csv", index=False)

In [37]:
model_protein_has_model_reaction_ng = pd.read_csv("ngaditana/model_protein_has_model_reaction.csv")
mdoel_protein_pl = pd.read_csv("plutheri/model_protein.csv")

In [38]:
model_protein_has_model_reaction_ng = model_protein_has_model_reaction_ng.loc[model_protein_has_model_reaction_ng.model_reaction_idreaction.isin(id_reaction_added.idreaction)]

In [39]:
model_protein_has_model_reaction_pl = model_protein_has_model_reaction_ng[['model_protein_idprotein', 'model_reaction_idreaction']].copy()
model_protein_has_model_reaction_pl.head()

      model_protein_idprotein  model_reaction_idreaction
1378                      544                      52905
1379                      544                      52906
1380                      544                      52907
1381                      544                      52908
1382                      544                      52909

In [40]:
# map model_protein_idprotein to new idprotein based on ec numbers that are in model_protein_pl and model_protein_has_model_reaction_ng
model_protein_has_model_reaction_pl_idprotein = model_protein_has_model_reaction_pl.copy()
model_protein_has_model_reaction_pl_idprotein['model_protein_idprotein'] = model_protein_has_model_reaction_ng['ecnumber'].map(mdoel_protein_pl.set_index('ecnumber')['idprotein']).astype('Int64')
model_protein_has_model_reaction_pl_idprotein.head()

      model_protein_idprotein  model_reaction_idreaction
1378                     1091                      52905
1379                     1091                      52906
1380                     1091                      52907
1381                     1091                      52908
1382                     1091                      52909

In [41]:
model_protein_has_model_reaction_pl.tail()

       model_protein_idprotein  model_reaction_idreaction
20470                     7730                      53295
20986                     7819                      42703
20990                     7842                      45376
20991                     7851                      42704
20992                     7851                      42705

In [42]:
model_protein_has_model_reaction_pl_idprotein.tail() # BMGR6174

       model_protein_idprotein  model_reaction_idreaction
20470                     7645                      53295
20986                     7904                      42703
20990                     7973                      45376
20991                     7911                      42704
20992                     7911                      42705

In [43]:
model_protein_has_model_reaction_pl_idreaction = model_protein_has_model_reaction_pl_idprotein.copy()
# update model_reaction_idreaction from model_reaction_reaction_labels_pl_added old_idreaction to idreaction
model_protein_has_model_reaction_pl_idreaction['model_reaction_idreaction'] = model_protein_has_model_reaction_pl_idreaction['model_reaction_idreaction'].map(model_reaction_reaction_labels_pl_added.set_index('old_idreaction')['idreaction'])

In [44]:
model_protein_has_model_reaction_pl_idreaction.tail() # 19905 -> BMGR6174

       model_protein_idprotein  model_reaction_idreaction
20470                     7645                      19905
20986                     7904                      13670
20990                     7973                      13767
20991                     7911                      13671
20992                     7911                      13672

In [45]:
model_protein_has_model_reaction_pl_idreaction.to_csv("plutheri/model_protein_has_model_reaction_to_add.csv", index=False)

In [102]:
model_pathway_pl = pd.read_csv("plutheri/model_pathway.csv")
model_pathway_has_reaction_pl = pd.read_csv("plutheri/model_pathway_has_reaction.csv")
model_pathway_has_reaction_ng = pd.read_csv("ngaditana/model_pathway_has_reaction.csv")

In [103]:
pathways_to_add = model_pathway_has_reaction_ng.loc[~model_pathway_has_reaction_ng.name.isin(model_pathway_pl.name)]
# drop duplicate names, keeping first
pathways_to_add_no_duplicated = pathways_to_add.drop_duplicates(subset="name", keep="first")
pathways_to_add_no_duplicated.head()

Empty DataFrame
Columns: [idpathway, code, image, name, path_sbml_file, pathway_idpathway, reaction_idreaction]
Index: []

In [109]:
model_pathway_has_reaction_pl_to_add = model_pathway_has_reaction_ng.copy()
# update model_pathway_idpathway from model_pathway_has_reaction_ng name to idpathway
model_pathway_has_reaction_pl_to_add['model_pathway_idpathway_new'] = model_pathway_has_reaction_pl_to_add['name'].map(model_pathway_pl.set_index('name')['idpathway'])

In [110]:
model_pathway_has_reaction_pl_to_add.head()

,idpathway,code,image,name,path_sbml_file,pathway_idpathway,reaction_idreaction,model_pathway_idpathway_new
0,9,00710,NaN,Carbon fixation in photosynthetic organisms,NaN,9,321,17
1,9,00710,NaN,Carbon fixation in photosynthetic organisms,NaN,9,323,17
2,9,00710,NaN,Carbon fixation in photosynthetic organisms,NaN,9,330,17
3,9,00710,NaN,Carbon fixation in photosynthetic organisms,NaN,9,331,17
4,9,00710,NaN,Carbon fixation in photosynthetic organisms,NaN,9,350,17

In [118]:
# update reaction_idreaction using the old_idreaction from model_reaction_reaction_labels_pl_added
model_pathway_has_reaction_pl_to_add_idreaction = model_pathway_has_reaction_pl_to_add.copy()
model_pathway_has_reaction_pl_to_add_idreaction['model_reaction_idreaction'] = model_pathway_has_reaction_pl_to_add_idreaction['reaction_idreaction'].map(model_reaction_reaction_labels_pl_added.set_index('old_idreaction')['idreaction'])

In [119]:
model_pathway_has_reaction_pl_to_add_idreaction.model_reaction_idreaction = model_pathway_has_reaction_pl_to_add_idreaction.model_reaction_idreaction.astype('Int64')
# drop rows with nan in model_reaction_idreaction
model_pathway_has_reaction_pl_to_add_idreaction = model_pathway_has_reaction_pl_to_add_idreaction.dropna(subset=['model_reaction_idreaction'])
model_pathway_has_reaction_pl_to_add_idreaction.drop(["idpathway", "code", "image", "name", "path_sbml_file", "pathway_idpathway", "reaction_idreaction"], axis=1, inplace=True)

In [124]:
model_pathway_has_reaction_pl_to_add_idreaction.to_csv("plutheri/model_pathway_has_reaction_to_add.csv", index=False)

In [59]:
model_stoichiometry_ng_idcompound[model_stoichiometry_ng_idcompound.model_compound_idcompound.isna()]

,idstoichiometry,stoichiometric_coefficient,model_compartment_idcompartment,model_compound_idcompound,model_reaction_idreaction
80678,144786,-1.0,1,<NA>,12716
80680,144788,1.0,1,<NA>,12716
86924,151732,-1.0,1,<NA>,12717
86926,151734,1.0,1,<NA>,12717
100466,175976,-1.0,1,<NA>,13431
...,...,...,...,...,...
174982,386890,-1.0,1,<NA>,19679
174986,386894,-1.0,1,<NA>,19680
174990,386898,1.0,1,<NA>,19680
174996,386904,-1.0,1,<NA>,19681
174997,386905,1.0,1,<NA>,19681